//! bit-typing core library: settings, courses, i18n, session engine, paths.
//!
//! The GUI (`src/main.rs`, `src/app.rs`) is a thin egui layer over this logic,
//! mirroring the behaviour of the original Python `main.py`.

pub mod app;
pub mod audio;
pub mod courses;
pub mod history;
pub mod i18n;
pub mod keyboards;
pub mod paths;
pub mod session;
pub mod settings;
pub mod theme;

pub use paths::{APP_NAME, APP_VERSION, APP_WEBSITE};

use rust_embed::RustEmbed;

/// Compile-time embedded defaults, mirroring PyInstaller's `_MEIPASS` bundle.
///
/// At runtime [`paths::ensure_dirs`] copies these into the writable
/// [`paths::runtime_root`] without overwriting user edits.
#[derive(RustEmbed)]
#[folder = "courses"]
#[prefix = "courses/"]
#[include = "*.txt"]
pub struct EmbeddedCourses;

#[derive(RustEmbed)]
#[folder = "lang"]
#[prefix = "lang/"]
#[include = "*.json"]
pub struct EmbeddedLangs;

#[derive(RustEmbed)]
#[folder = "keyboards"]
#[prefix = "keyboards/"]
#[include = "*.json"]
pub struct EmbeddedKeyboards;

#[derive(RustEmbed)]
#[folder = "assets"]
#[prefix = "assets/"]
#[include = "*.png"]
pub struct EmbeddedAssets;

#[derive(RustEmbed)]
#[folder = "data/sounds"]
#[prefix = "data/sounds/"]
#[include = "*.wav"]
pub struct EmbeddedSounds;

/// SHA-256 manifest generated by `build.rs` (`default-resources.json`).
pub fn default_resources_manifest() -> serde_json::Value {
    let path = env!("BIT_TYPING_DEFAULT_RESOURCES");
    serde_json::from_str(
        &std::fs::read_to_string(path).expect("default-resources manifest"),
    )
    .expect("parse manifest")
}
